services:
  - type: web
    name: pure-pleasure-frontend
    env: static
    buildCommand: npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://interior-design-6mqd.onrender.com